name: CI

on: [push, pull_request]

jobs:
  build:
    name: '${{ matrix.os }} : ${{ matrix.sanitizer }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest, windows-latest]
        sanitizer: [none, asan]
        exclude:
          - os: macos-latest
            sanitizer: asan
          - os: windows-latest
            sanitizer: asan
    env:
      SANITIZER: ${{ matrix.sanitizer }}
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '2.7'
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: mkdir
      run: mkdir -p out
    - name: cmake
      run: cmake ..
      working-directory: out
    - name: build
      run: cmake --build out
    - name: test
      run: cmake --build out --target run-tests
